### ISSUE TITLE
Requesting Attachment of Document like PDF

### ISSUE THREAD

**Issue by JaganVJ1998** [Jaganv1998/Whatup_Update#5]
Dear Jagan
 
You can add the attachment of the document in the whatsup. Kindly add this feature

**Comment by Jaganv1998** [comment]
Thanks for your ideas and knowledge

**Comment by Jaganv1998** [comment]
Thanks for your suggesting this feature. We will add and let you know.

**Comment by Jaganv1998** [comment]
Thanks for available suggestion

**Comment by Jaganv1998** [comment]
Done
